version: "3.3"
services:
  nginx:
    image: 7100071/devops
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    container_name: nginx-container
    ports:
      - 80:80
    links:
      - php
    volumes:  
      - ./website/:/var/www/html/ 
  php:
    image: php:7.0-fpm
    container_name: php-container
    expose:
      - 9000
    volumes:  
      - ./website/:/var/www/html/ 
